# Generated by Django 3.2.16 on 2023-02-19 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pairleary_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='matched_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
