# Generated by Django 3.2.16 on 2023-02-15 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pairleary_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(help_text='予約日付')),
                ('order_time_range_type', models.CharField(default='null', max_length=10)),
                ('category', models.CharField(default='null', max_length=150)),
                ('hope_gender_type', models.CharField(blank=True, choices=[(None, '-'), ('m', '男性'), ('f', '女性')], default=None, max_length=1, null=True, verbose_name='性別')),
                ('comment', models.CharField(default='null', max_length=255)),
                ('matched_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_user_id', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
