# Generated by Django 3.2.16 on 2023-02-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairleary_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_time_range_type',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
