# Generated by Django 3.2.16 on 2023-01-29 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pairleary_app', '0002_auto_20230130_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('condition_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='null', max_length=150)),
                ('comment', models.CharField(default='null', max_length=255)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
