# Generated by Django 3.2.16 on 2023-01-29 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pairleary_app', '0003_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='condition_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pairleary_app.conditions'),
        ),
    ]
