# Generated by Django 3.2.16 on 2023-02-13 00:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pairleary_app', '0003_alter_orders_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='予約日付'),
        ),
    ]
