# Generated by Django 3.2.16 on 2023-01-29 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pairleary_app', '0004_orders_condition_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
