# Generated by Django 3.2.16 on 2023-02-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairleary_app', '0004_alter_orders_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateField(help_text='予約日付'),
        ),
    ]
