# Generated by Django 3.2.16 on 2023-01-31 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pairleary_app', '0005_delete_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(help_text='予約日付')),
                ('order_time_start', models.DateTimeField(help_text='予約開始時間')),
                ('order_time_end', models.DateTimeField(help_text='予約終了時間')),
                ('condition_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pairleary_app.conditions')),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('condition_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pairleary_app.conditions')),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pairleary_app.orders')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
